version: "3"

dotenv: [".env"]

vars:
  SERVICE_NAME: db-service
  SERVICE_DIR: db-service
  DOCKER_COMPOSE: docker compose

tasks:

  default:
    desc: "Показать список задач"
    cmds:
      - task --list

  # ------------------------
  #  PROTO
  # ------------------------

  proto:
    desc: "Generate gRPC code from proto files"
    dir: "{{.SERVICE_DIR}}"
    cmds:
      - |
        protoc \
          --go_out=. \
          --go-grpc_out=. \
          proto/*.proto

  # ------------------------
  #  DATABASE
  # ------------------------

  db:up:
    desc: "Start postgres"
    cmds:
      - "{{.DOCKER_COMPOSE}} up -d postgres"

  db:down:
    desc: "Stop postgres"
    cmds:
      - "{{.DOCKER_COMPOSE}} down"

  db:logs:
    desc: "Postgres logs"
    cmds:
      - "{{.DOCKER_COMPOSE}} logs -f postgres"

  # ------------------------
  #  LOCAL RUN
  # ------------------------

  run:
    desc: "Run db-service locally"
    dir: "{{.SERVICE_DIR}}"
    cmds:
      - go run ./cmd/db-service

  # ------------------------
  #  DOCKER
  # ------------------------

  docker:build:
    desc: "Build db-service docker image"
    cmds:
      - "{{.DOCKER_COMPOSE}} build {{.SERVICE_NAME}}"

  docker:up:
    desc: "Run all services in docker"
    cmds:
      - "{{.DOCKER_COMPOSE}} up -d"

  docker:down:
    desc: "Stop all docker services"
    cmds:
      - "{{.DOCKER_COMPOSE}} down"

  docker:logs:
    desc: "Logs from db-service"
    cmds:
      - "{{.DOCKER_COMPOSE}} logs -f {{.SERVICE_NAME}}"

  # ------------------------
  #  TESTS
  # ------------------------

  test:
    desc: "Run all tests"
    dir: "{{.SERVICE_DIR}}"
    cmds:
      - go test ./... -v

  # ------------------------
  #  CLEAN
  # ------------------------

  clean:
    desc: "Clean build artifacts"
    cmds:
      - rm -rf {{.SERVICE_DIR}}/bin
