version: "3"

dotenv: [".env"]

vars:
  DB_SERVICE_NAME: db-service
  DB_SERVICE_DIR: db-service
  API_SERVICE_NAME: api-service
  API_SERVICE_DIR: api-service
  DOCKER_COMPOSE: docker compose

tasks:

  default:
    desc: "Показать список задач"
    cmds:
      - task --list

  # ------------------------
  #  PROTO
  # ------------------------

  proto:
    desc: "Generate gRPC code from proto files"
    dir: "{{.DB_SERVICE_DIR}}"
    cmds:
      - |
        protoc \
          --go_out=. \
          --go-grpc_out=. \
          proto/*.proto

  # ------------------------
  #  DATABASE
  # ------------------------

  db:up:
    desc: "Start postgres"
    cmds:
      - "{{.DOCKER_COMPOSE}} up -d postgres"

  db:down:
    desc: "Stop postgres"
    cmds:
      - "{{.DOCKER_COMPOSE}} down"

  db:logs:
    desc: "Postgres logs"
    cmds:
      - "{{.DOCKER_COMPOSE}} logs -f postgres"

  # ------------------------
  #  LOCAL RUN
  # ------------------------

  run:db:
    desc: "Run db-service locally"
    dir: "{{.DB_SERVICE_DIR}}"
    cmds:
      - go run ./cmd/db-service

  run:api:
    desc: "Run api-service locally"
    dir: "{{.API_SERVICE_DIR}}"
    cmds:
      - go run ./cmd/api

  # ------------------------
  #  DOCKER
  # ------------------------

  docker:build:
    desc: "Build db-service docker image"
    cmds:
      - "{{.DOCKER_COMPOSE}} build {{.DB_SERVICE_NAME}}"

  docker:build:api:
    desc: "Build api-service docker image"
    cmds:
      - "{{.DOCKER_COMPOSE}} build {{.API_SERVICE_NAME}}"

  docker:up:
    desc: "Run all services in docker"
    cmds:
      - "{{.DOCKER_COMPOSE}} up -d"

  docker:up:api:
    desc: "Run api-service in docker (requires db-service running)"
    cmds:
      - "{{.DOCKER_COMPOSE}} up -d {{.API_SERVICE_NAME}}"

  docker:down:
    desc: "Stop all docker services"
    cmds:
      - "{{.DOCKER_COMPOSE}} down"

  docker:logs:
    desc: "Logs from db-service"
    cmds:
      - "{{.DOCKER_COMPOSE}} logs -f {{.DB_SERVICE_NAME}}"

  docker:logs:api:
    desc: "Logs from api-service"
    cmds:
      - "{{.DOCKER_COMPOSE}} logs -f {{.API_SERVICE_NAME}}"

  # ------------------------
  #  TESTS
  # ------------------------

  test:
    desc: "Run all tests"
    dir: "{{.DB_SERVICE_DIR}}"
    cmds:
      - go test ./... -v

  # ------------------------
  #  CLEAN
  # ------------------------

  clean:
    desc: "Clean build artifacts"
    cmds:
      - rm -rf {{.DB_SERVICE_DIR}}/bin