// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	proto "github.com/N0F1X3d/todo/pkg/proto"
	mock "github.com/stretchr/testify/mock"
)

// TaskServerInterface is an autogenerated mock type for the TaskServerInterface type
type TaskServerInterface struct {
	mock.Mock
}

// CompleteTask provides a mock function with given fields: ctx, req
func (_m *TaskServerInterface) CompleteTask(ctx context.Context, req *proto.CompleteTaskRequest) (*proto.TaskResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CompleteTask")
	}

	var r0 *proto.TaskResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.CompleteTaskRequest) (*proto.TaskResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.CompleteTaskRequest) *proto.TaskResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.TaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.CompleteTaskRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateTask provides a mock function with given fields: ctx, req
func (_m *TaskServerInterface) CreateTask(ctx context.Context, req *proto.CreateTaskRequest) (*proto.TaskResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 *proto.TaskResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.CreateTaskRequest) (*proto.TaskResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.CreateTaskRequest) *proto.TaskResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.TaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.CreateTaskRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTask provides a mock function with given fields: ctx, req
func (_m *TaskServerInterface) DeleteTask(ctx context.Context, req *proto.DeleteTaskRequest) (*proto.DeleteTaskResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 *proto.DeleteTaskResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.DeleteTaskRequest) (*proto.DeleteTaskResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.DeleteTaskRequest) *proto.DeleteTaskResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.DeleteTaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.DeleteTaskRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllTasks provides a mock function with given fields: ctx, req
func (_m *TaskServerInterface) GetAllTasks(ctx context.Context, req *proto.GetAllTasksRequest) (*proto.GetAllTasksResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTasks")
	}

	var r0 *proto.GetAllTasksResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.GetAllTasksRequest) (*proto.GetAllTasksResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.GetAllTasksRequest) *proto.GetAllTasksResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.GetAllTasksResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.GetAllTasksRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTaskByID provides a mock function with given fields: ctx, req
func (_m *TaskServerInterface) GetTaskByID(ctx context.Context, req *proto.GetTaskByIDRequest) (*proto.TaskResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskByID")
	}

	var r0 *proto.TaskResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.GetTaskByIDRequest) (*proto.TaskResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.GetTaskByIDRequest) *proto.TaskResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.TaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.GetTaskByIDRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedTaskServiceServer provides a mock function with no fields
func (_m *TaskServerInterface) mustEmbedUnimplementedTaskServiceServer() {
	_m.Called()
}

// NewTaskServerInterface creates a new instance of TaskServerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskServerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskServerInterface {
	mock := &TaskServerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
